### ISSUE TITLE
Support for Argo Workflows?

### ISSUE THREAD

**Issue by MattHodge** [haxsaw/hikaru#29]
Hi There,

Based on how Hikaru is using OpenAPI/Swagger specs to generate types, would you consider supporting Argo Workflows? ([Swagger 2.0 Spec](https://raw.githubusercontent.com/argoproj/argo-workflows/master/api/openapi-spec/swagger.json)).

If not, is there any way to generate my own types and use them with Hikaru?

Thanks!

**Comment by haxsaw** [comment]
Let me have a look. Hikaru's build system doesn't handle all of JSON Schema,  just the idiosyncratic use made by Kubernetes. This means the builder may not be able to generate Python properly or that it will work with the rest of Hikaru without modification. General JSON Schema support is on my radar in order to provide more seamless CRD support, but as I study the problem it's a big job. Your question is leading me to wonder if a more incremental approach. So let me have a tinker and I'll post what I find.

**Comment by haxsaw** [comment]
For the benefit of those who might be following this thread: I think I need a page that addresses "Can I use Hikaru to process the swagger for project X?" questions that arise from time to time. The answer is "maybe, but..."

The Kubernetes swagger has some specifc properties that allow Hikaru to turn that swagger into a swath of Python classes with methods:

- K8s comprehensively creates JSON Schema definitions for every object that it uses; there are no naked JSON objects anywhere in the swagger-- if a piece of data is structured at all, uses of that data involve a reference to a definition.
- K8s uses those definitions not only in the definitions of more complex objects, but more importantly as the primary argument to an operation. This allows me to associate the operation with an object, and is how we establish class and instance methods for these operations on the generated Hikaru classes.
- K8s provides a generally consistent set of naming conventions that allow you to tie an operation with a function or method in the underlying K8s Python client. Eventually this will be less of an issue when Hikaru grows to simply use the underlying generic request mechanisms in the K8s client, but for now it uses this information to short-cut to methods that wrap these base facilities.

These properties are what allows Hikaru's builder do what it does with the K8s swagger easily. The JSON Schema spec used within swagger allows a lot more uses such as in-lined descriptions of complex objects for operations that would thwart things like automatic method creation on an object, and definition-less specifiction of objects that are used as parameters to operations or components to other objects.

It certainly is possible to create a parsing system that produced a structure that the user could then fill in missing object details or otherwise supply info that isn't in the swagger in order to allow the creation of a similar set of classes to those of Hikaru. This sort of use has been on my mind as it has direct applicability to richer support for CRDs. It is also a somewhat complex problem with a lot of work involved.

So what am I telling everyone here? I'm trying to set expectations. I welcome requests regarding the possibility of Hikaru supporting another swagger file and will take some time to have a look at what sort of issues lurk within, but I can tell you that, so far, I haven't come across any other requested swagger that Hikaru's builder can easily adapt to. Additionally, K8s has some idiosyncratic conventions that I leverage, and other swagger may not have those (or may have entirely different ones), and those take time to understand and adapt to.

So one thing people who request support may want to consider is how they can get some 'skin in the game', either by providing research or coding capacity to support this different swagger, or consider if their need is significant enough that they would be willing to enter a commercial arrangement with me to pursue this work for them.

As for the above Argo support request, I can share the following update for those who are interested: I've gotten some way through processing the Argo swagger and have had to only make minimal changes to the builder. But at the moment I'm stopped by an unexpected notation in how results may be reported, as the Argo API has some results that  aren't HTTP status codes, and I need someone to look into these to determine the semantic so I can understand how they should be handled. Additionally, I see more than a few operations that don't use defined types but just a set of parameters, so something new will need to be added in the case of an operation that can't be turned into a method automatically. I've invited @MattHodge to continue the details of this outside of this thread and will update here depending on how those discussions go.

**Comment by haxsaw** [comment]
This hasn't received any community support, so I'm considering closing this item unless someone can help out.

**Comment by haxsaw** [comment]
Closing due to apparent lack of interest by the original author.
